# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swifty-Companion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swifty-Companion
  pod 'Alamofire', '4.4.0'
  pod 'AlamofireSwiftyJSON'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
end
